import { Job, Inquiry, TenantSettings } from "@/types/crm";

export const initialTenantSettings: TenantSettings = {
  id: "tenant-1",
  name: "Kristály Szőnyegtisztító Kft.",
  slug: "kristaly-szonyeg",
  plan: "STARTER",
  monthlyJobsCount: 48,
  maxMonthlyJobs: 200,
  monthlyLeadsCount: 62,
  maxMonthlyLeads: 300,
  seatsCount: 1,
  maxSeats: 1,
  aiCredits: 28, // 30-ból 2 elhasználva
  autoAiResponse: false,
  phone: "+36 30 456 7890",
  email: "info@kristalyszonyeg.hu",
  address: "1117 Budapest, Fehérvári út 84.",
  googleReviewUrl: "https://maps.google.com/?q=Kristaly+Szonyegtisztito",
  facebookReviewUrl: "https://facebook.com/kristalyszonyeg",
  invoiceProvider: "SZAMLAZZ",
};

export const initialJobs: Job[] = [
  {
    id: "job-101",
    jobCode: "CF-2026-0048",
    status: "WAITING_PICKUP",
    pickupMode: "QUICK_COUNT",
    quickRugCount: 3,
    customerId: "cust-1",
    customerName: "Kovács Katalin",
    customerPhone: "+36 30 112 3344",
    customerAddress: "Bartók Béla út 52. 3/14",
    customerCity: "Budapest",
    customerNotes: "Kutya van, kapucsengő: 14. 16:00 után ér rá.",
    scheduledPickup: "2026-09-16 16:30",
    assignedDriver: "Nagy Zoltán (1-es furgon)",
    items: [],
    totalAmount: 0,
    paymentMethod: "CASH",
    paymentStatus: "PENDING",
    trackingToken: "trk-a8f9c2d1",
    createdAt: "2026-09-15 10:15",
  },
  {
    id: "job-102",
    jobCode: "CF-2026-0047",
    status: "RECEIVED",
    pickupMode: "FIELD_MEASURED",
    customerId: "cust-2",
    customerName: "Horváth Gábor",
    customerPhone: "+36 20 987 6543",
    customerAddress: "Karinthy Frigyes út 12. 1/4",
    customerCity: "Budapest",
    customerNotes: "Erősen koszos előszobai szőnyegek.",
    scheduledPickup: "2026-09-15 09:00",
    scheduledDelivery: "2026-09-19 14:00",
    assignedDriver: "Nagy Zoltán (1-es furgon)",
    items: [
      {
        id: "item-1",
        name: "Shaggy hosszúszálú szőnyeg",
        width: 2.0,
        length: 3.0,
        area: 6.0,
        basePricePerM2: 2800,
        isHeavySoiling: true,
        heavySoilingFee: 4000,
        extras: ["Atkamentesítés (antibakteriális)"],
        extrasFee: 3000,
        totalPrice: 23800,
        tagQrCode: "QR-0047-1",
      },
      {
        id: "item-2",
        name: "Rongyszőnyeg futó",
        width: 0.8,
        length: 2.5,
        area: 2.0,
        basePricePerM2: 2200,
        isHeavySoiling: false,
        heavySoilingFee: 0,
        extras: [],
        extrasFee: 0,
        totalPrice: 4400,
        tagQrCode: "QR-0047-2",
      },
    ],
    totalAmount: 28200,
    paymentMethod: "CARD_POS",
    paymentStatus: "PENDING",
    trackingToken: "trk-b7e1f489",
    createdAt: "2026-09-14 14:20",
  },
  {
    id: "job-103",
    jobCode: "CF-2026-0046",
    status: "IN_PROGRESS",
    pickupMode: "FIELD_MEASURED",
    customerId: "cust-3",
    customerName: "Dr. Varga Tamás",
    customerPhone: "+36 70 334 5566",
    customerAddress: "Villányi út 34.",
    customerCity: "Budapest",
    scheduledDelivery: "2026-09-18 11:00",
    assignedDriver: "Nagy Zoltán (1-es furgon)",
    items: [
      {
        id: "item-3",
        name: "Kézi csomózású perzsa szőnyeg",
        width: 2.5,
        length: 3.5,
        area: 8.75,
        basePricePerM2: 4500,
        isHeavySoiling: false,
        heavySoilingFee: 0,
        extras: ["Ózonos fertőtlenítés", "Bojt tisztítás"],
        extrasFee: 7000,
        totalPrice: 46375,
        tagQrCode: "QR-0046-1",
      },
    ],
    totalAmount: 46375,
    paymentMethod: "TRANSFER",
    paymentStatus: "PAID",
    trackingToken: "trk-c3d5a712",
    createdAt: "2026-09-13 11:00",
  },
  {
    id: "job-104",
    jobCode: "CF-2026-0045",
    status: "COMPLETED",
    pickupMode: "FIELD_MEASURED",
    customerId: "cust-4",
    customerName: "Molnár Eszter",
    customerPhone: "+36 30 778 9900",
    customerAddress: "Alkotás utca 17.",
    customerCity: "Budapest",
    scheduledDelivery: "2026-09-16 10:00",
    assignedDriver: "Nagy Zoltán (1-es furgon)",
    items: [
      {
        id: "item-4",
        name: "Normál rövid szálú szőnyeg",
        width: 1.6,
        length: 2.3,
        area: 3.68,
        basePricePerM2: 2400,
        isHeavySoiling: false,
        heavySoilingFee: 0,
        extras: ["Szagtalanítás"],
        extrasFee: 2500,
        totalPrice: 11332,
        tagQrCode: "QR-0045-1",
      },
    ],
    totalAmount: 11332,
    paymentMethod: "CASH",
    paymentStatus: "PENDING",
    trackingToken: "trk-d9f2b184",
    createdAt: "2026-09-12 16:40",
  },
  {
    id: "job-105",
    jobCode: "CF-2026-0044",
    status: "DELIVERED",
    pickupMode: "FIELD_MEASURED",
    customerId: "cust-5",
    customerName: "Tóth Béla",
    customerPhone: "+36 20 445 6677",
    customerAddress: "Móricz Zsigmond körtér 8.",
    customerCity: "Budapest",
    scheduledDelivery: "2026-09-14 15:30",
    assignedDriver: "Nagy Zoltán (1-es furgon)",
    items: [
      {
        id: "item-5",
        name: "Gyapjú padlószőnyeg",
        width: 3.0,
        length: 4.0,
        area: 12.0,
        basePricePerM2: 3200,
        isHeavySoiling: false,
        heavySoilingFee: 0,
        extras: ["Impregnálás"],
        extrasFee: 6000,
        totalPrice: 44400,
        tagQrCode: "QR-0044-1",
      },
    ],
    totalAmount: 44400,
    paymentMethod: "TRANSFER",
    paymentStatus: "PAID",
    invoiceNumber: "SZAM-2026/044",
    trackingToken: "trk-e5a1c903",
    createdAt: "2026-09-10 09:10",
  },
];

export const initialInquiries: Inquiry[] = [
  {
    id: "inq-1",
    source: "WEB_WIDGET",
    customerName: "Szabó Andrea",
    customerPhone: "+36 30 998 1122",
    customerEmail: "szabo.andrea@gmail.com",
    customerAddress: "1124 Budapest, Németvölgyi út 45.",
    customerNotes: "Két shaggy szőnyeg, az egyiken kávéfolt van. 2x3m és 1.5x2m.",
    estimatedAmount: 32500,
    itemsPreview: "2 db szőnyeg (~9.0 m²)",
    preferredDate: "2026-09-17",
    status: "NEW",
    aiSummary: "Felismerve: 2 db Shaggy szőnyeg (össz. 9 m²). Folt: kávé (speciális folttisztító kezelés javasolt). Várható kalkuláció: 32 500 Ft.",
    aiDraftReply: "Kedves Andrea!\n\nKöszönjük megkeresését! A 2 db Shaggy szőnyeg (2x3m és 1.5x2m) tisztítását, valamint a kávéfolt szakszerű mélytisztítását örömmel vállaljuk.\n\nA várható végösszeg kb. 32 500 Ft (elszállítással és visszaszállítással együtt). A kért szeptember 17-i napon délelőtt 9:00 és 12:00 között tudnánk felvenni a szőnyegeket.\n\nKérjük, jelezzen vissza, ha az időpont megfelel Önnek!\n\nÜdvözlettel,\nKristály Szőnyegtisztító Csapata",
    createdAt: "2026-09-15 15:40",
  },
  {
    id: "inq-2",
    source: "EMAIL",
    customerName: "Pintér Ferenc",
    customerPhone: "+36 70 556 7788",
    customerEmail: "pinter.f@iroda.hu",
    customerAddress: "1118 Budapest, Rétköz utca 12.",
    customerNotes: "Irodai tárgyaló perzsaszőnyeg tisztítása és atkamentesítése.",
    estimatedAmount: 48000,
    itemsPreview: "1 db nagy perzsa szőnyeg (3x4m)",
    preferredDate: "2026-09-18",
    status: "OFFER_SENT",
    aiSummary: "Felismerve: 1 db Prémium perzsa szőnyeg (12 m²) + Atkamentesítés. Céges ügyfél, átutalásos számlát igényel.",
    aiDraftReply: "Tisztelt Pintér Ferenc!\n\nIrodai tárgyalójuk perzsaszőnyegének professzionális tisztítására és atkamentesítésére a hivatalos árajánlatunk 48 000 Ft + ÁFA. A munkáról átutalásos számlát állítunk ki.\n\nVárjuk szíves visszajelzésüket a felvétel ütemezéséhez!",
    createdAt: "2026-09-15 11:20",
  },
];

export const rugPriceCatalog = [
  { id: "p-1", name: "Normál rövid szálú szőnyeg", unitPrice: 2400, unit: "Ft / m²", description: "Standard síkszövött vagy hurkolt szőnyegek" },
  { id: "p-2", name: "Shaggy hosszú szálú szőnyeg", unitPrice: 2800, unit: "Ft / m²", description: "Hosszú szálas, sűrű szövésű modern szőnyegek" },
  { id: "p-3", name: "Gyapjú szőnyeg", unitPrice: 3200, unit: "Ft / m²", description: "Természetes gyapjú, kímélő semleges pH mosószerrel" },
  { id: "p-4", name: "Kézi csomózású Perzsa szőnyeg", unitPrice: 4500, unit: "Ft / m²", description: "Értékes keleti, selyem vagy antik szőnyegek kímélő kézi mosása" },
  { id: "p-5", name: "Padlószőnyeg / Rongyszőnyeg", unitPrice: 2200, unit: "Ft / m²", description: "Vékonyabb pamut és szintetikus futók" },
];

export const extrasCatalog = [
  { id: "e-1", name: "Erős szennyezettségi felár", unitPrice: 800, unit: "Ft / m²", description: "Sár, beivódott zsíros kosz, építkezési por" },
  { id: "e-2", name: "Ózonos szagtalanítás & fertőtlenítés", unitPrice: 3500, unit: "Ft / db", description: "Dohányfüst, penész és makacs szagok semlegesítése" },
  { id: "e-3", name: "Antibakteriális Atkamentesítés", unitPrice: 3000, unit: "Ft / db", description: "Allergiásoknak és kisgyermekes családoknak javasolt" },
  { id: "e-4", name: "Kisállat vizelet / folt neutralizálás", unitPrice: 4500, unit: "Ft / db", description: "Enzimes lebontó kezelés" },
  { id: "e-5", name: "Védő Impregnálás", unitPrice: 1200, unit: "Ft / m²", description: "Folyadéklepergető nano védőréteg felvitele" },
];
